[package]
name = "nes"
version = "0.1.0"
authors = ["Thierry Doornbos <t.doornbos95@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.31"
bitflags = "1.2.1"
getset = "0.1.1"
tui = { version = "0.10.0", default-features = false, features = ["crossterm"] }
crossterm = "0.17.7"
